input_path: 'input'
output_path: 'output'
recursive: true
extended_logger: true

include_all_files: false
include_extra_formats: ['.mp3', '.txt', '.json']

metadata_fixer:
  enabled: true
  fill_missing_datetime_info_from: ['filename']
  overwrite_datetime: false

file_organizer:
  enabled: false
  folder_structure: ['year', 'month']

duplicates_search:
  enabled: false
  hash_size: 16
  similarity: 96
  plot_before_confirm: true
