input_path: 'input'
output_path: 'output'
recursive: true
extended_logger: true
auto_clean_output: false

include_all_files: false
include_extra_formats: ['.mp3', '.txt', '.json']

metadata_fixer:
  enabled: true
  fill_missing_datetime_info_from: ['filename']
  overwrite_datetime: false

file_organizer:
  enabled: true
  folder_structure: ['%Y', '%m - %B']
  file_name_template: ''

duplicates_search:
  enabled: true
  hash_size: 16
  similarity: 96
  plot_before_confirm: true
