input_path: 'input'
output_path: 'output'
recursive: true
extended_logger: false

include_all_files: false
include_extra_formats: ['.mp3', '.txt', '.json']

datetime_fixer:
  enabled: true
  force: false

file_organizer:
  enabled: true
  folder_structure: ['year', 'month']

duplicates_search:
  enabled: true
  hash_size: 64
  similarity: 80
  plot_before_confirm: true
